# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'GithubUserRxSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubUserRxSwift
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Moya'
  pod 'Moya-ModelMapper/RxSwift'
  pod 'RxOptional'
  pod 'MBProgressHUD'
  
  target 'GithubUserRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
